#+TITLE: Duolingo is a Video Game
#+DATE: <2022-09-11 Sun>
#+TAGS[]: language
#+DRAFT: true

Do you ever wonder what a 2000-day streak on a Duolingo course would be like? You would be imagining that you would be extremely attractive to every single woman and man on the planet with your hyperpolyglot gigachad alpha male tongue.

But 99.9% of the time, that isn't the case.

A lot of people seem to have the misconception that Duolingo will teach you how to speak a language. Duolingo is a video game. The main issue with Duolingo is that you're learning how to /translate/ rather than learning how to /speak/ a language.

As you spend more time playing Duolingo, you have a false sense of achievement. It certainly does feel like you have learned something, but instead, all you have learned was to repeat the same five sentences. Even 2000-day streakers can make occasional grammar mistakes [[https://www.reddit.com/r/languagelearningjerk/comments/x7vmk3/op_cant_speak_fluently_and_only_understands_about/infz9oi/][FeelsBadMan]].

As you learn a language, you should ask yourself: am I thinking in my target language as I read?  Let's take this example sentence in Latin.

...

** Postscript: Duolingo Stories

A feature I had loved in Duolingo was its Stories. Yes, Duolingo still has them. But about a year ago, they had changed it so you have to complete a certain amount of crowns to unlock stories rather than finishing the previous stories.

This made it a lot difficult as I found Stories to be far more useful learning the conversational, spoken part of the language and understanding nuance and tone.

* What should I use Duolingo for then?

As stated before, Duolingo is a video game. You can learn the basics of a language with it pretty fast. However, please do not rely on Duolingo to achieve fluency.

And for some languages, it will instead develop nasty translation habits (looking at you, Latin) that would hinder your progress rather than help you grasp a good natural understanding of the language.

Depending on the language, it's best that you learn it in context, especially through the [[https://en.wikipedia.org/wiki/Direct_method_(education)][direct method]].
