#+TITLE: The Fish and Young Argument
#+DATE: <2022-09-09 Fri>
#+TAGS: english language

What is the write way to right?

Stanley Fish argues grammar is structure is essential to English composition. He supports the idea that teaching a /correct/ grammar is essential to teaching composition, and all college composition classes should teach the traditional forms of English grammar for academic writing.

He believes that teaching the "proper" form of English isn't robbing people of whatever dialect of English that they use. Rather, they are learning a new language alongside. This is particularly controversial as it becomes a cultural value.

However, Vershawn Ashanti Young instead claims that English composition should be taught by "code meshing" or blending dialects together, borrowing elements from each other. He argues this would bridge cultural differences and serve as a more diverse way of teaching English.

Rather than there being a standard form of English that everyone must conform to, everyone should be free to speak their own English, sometimes mixing in other dialects.

Many linguists (or at least most descriptivists) would agree that *there is no correct form of English*. There are many different dialects, and each has its own rules. The idea of a "standard" English is more of a social construct than anything else.

But of course, how you write very much depends on your *rhetorical situation*.

To whom are you writing? The idea that there isn't a correct form of English is absolutely correct. However, depending on who you are writing to, it is better to stick to an appropriate style. Even the type of English you would find in a legal document has completely different diction and sentence structures than what people would generally agree would be "standard English".

What should be taught is how different sentence structures, rhetorical choices, and methods of English affect the meaning, the speaker's message, and how it relates to the audience.
